### 

POST localhost:3001/monitor HTTP/1.1
Content-Type: application/json

{
  "selector": {
    "content": ".device-stats-wrapper",
    "title": ".device-header"
  },
  "site": "https://en.tankiwiki.com/Augments"
}


### 

POST localhost:3001/monitor HTTP/1.1
Content-Type: application/json

{"site": "https://www.baidu.com"}


### 

POST localhost:3001/monitor HTTP/1.1
Content-Type: application/json

{
  "selector": {
    "content": ".btzy",
    "title": ".timebox"
  },
  "site": "https://foaie.ccnu.edu.cn/xwzx/tzgg.htm"
}
